type:
  _target_: roleplay.models.openai_model.OpenAIModel
openai_api_type: "azure"
openai_api_version: "2023-05-15"
azure_openai_endpoint: null
azure_openai_api_key: null
name: "gpt-4"
context_length: 8192
non_coherent_max_n: 4
non_coherent_r: 2
regenerate_tries: null
generate:
  max_new_tokens: 1000
#   temperature: 0.8
#   top_p: 0.7
conv_template:
  system_prompt: 'You are <PERSONA>. You will start a conversation with an assistant. If you accomplish your ultimate goal during the conversation only say "<CONV_STOP>".'
  first_turn_input: "Your ultimate goal is as follows: <OBJECTIVE>. What prompt will you use to direct the assistant toward achieving your goal? Please provide the prompt within double quotes. Use simple language, keep the prompts brief, and be on point. Do not greet the assistant. Maintain a casual style; avoid being overly friendly, don't say thank you."
  n_th_turn_input: "<USER_MSG>"
  model_output: "<MODEL_ANSWER>"
  response_forwarding: "If the assistant didn't help you achieve your goal, ask follow-up or clarification questions within double quotes. Be suspicious, curious, and demanding. Keep it simple, brief, and to the point. Stay casual; avoid being overly friendly. Assistant response: \n\n\"<RESPONSE>\"."
  idx_of_possible_prompt: 0
