defaults:
  - _self_
  - action_config: defaults

action_name: ???

aim:
  repo: "aim://0.0.0.0:53800"

seed: 5

slurm:
  # Whether or not to run the job on SLURM
  use_slurm: false
  # Name of the job on SLURM
  name: "roleplay"
  # Comment of the job on SLURM
  comment: "roleplay job"
  # Partition of SLURM on which to run the job. This is a required field if using SLURM.
  partition: ""
  account: ""
  # Where the logs produced by the SLURM jobs will be output
  log_folder: "./slurm_logs"
  # Maximum number of hours / minutes needed by the job to complete. Above this limit, the job might be pre-empted.
  time_hours: 1
  time_minutes: 0
  # Additional constraints on the hardware of the nodes to allocate (roleplay 'volta' to select a volta GPU)
  constraint: ""
  # GB of RAM memory to allocate for each node
  mem_gb: 100
  # TCP port on which the workers will synchronize themselves with torch distributed
  port_id: 40050
  # Number of CPUs per GPUs to request on the cluster.
  num_cpu_per_proc: 4
  # Number of GPUs per node to request on the cluster.
  num_gpu_per_node: 4
  # Number of nodes to request on the cluster.
  num_nodes: 1
  # Number of processes per node to request on the cluster.
  num_proc_per_node: 1
  # Any other parameters for slurm (e.g. account, hint, distribution, etc.,) as dictated by submitit.
  # Please see https://github.com/facebookincubator/submitit/issues/23#issuecomment-695217824.
  additional_parameters: {}
