type:
  _target_: llm_roleplay.models.model_pipeline.ModelPipeline
name: "models--llama-2-hf/13B-Chat"
cache_dir: ""
dtype: torch.float16
non_coherent_max_n: 5
non_coherent_r: 2
api_token: null
generate:
  max_new_tokens: 4000
conv_template:
  first_turn_input: "[INST] <<SYS>>
    You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.

    If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.
    <</SYS>>

    <OBJECTIVE> [/INST]"
  n_th_turn_input: "[INST] <USER_MSG> [/INST]"
  model_output: "<MODEL_ANSWER>"
